# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# Change the following value to '/PROJECT_NAME' ONLY IF your site type is GitHub Pages Project sites
# and doesn't have a custom domain.
baseurl: ""

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: en

# Change to your timezone › http://www.timezoneconverter.com/cgi-bin/findzone/findzone
timezone: Asia/Shanghai

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Quafoo # the main title

tagline: Quafoo is a legendary character in a Chinese folk tale. He chases the sun in order to relieve the suffering of his people from the harsh drought. Chinese grandparents relate this story to their grandchildren in order to inspire them not to give up when chasing their goals. # it will display as the sub-title

description: >- # used by seo meta and the atom feed
  Welcome to Quafoo, a tech blog about AI and development.

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: "https://quafoo-net.github.io"

github:
  username: Quafoo # change to your github username

twitter:
  username: quafoo_net # change to your twitter username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Quafoo
  email: quafoo.net@gmail.com # change to your email address
  links:
    # The first element serves as the copyright owner's link
    - https://twitter.com/quafoo_net # change to your twitter homepage
    - https://github.com/quafoo-net # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

google_site_verification: # fill in to your verification string

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

google_analytics:
  id: G-HM6517G529 # fill in your Google Analytics ID
  # Google Analytics pageviews report settings
  pv:
    proxy_endpoint: # fill in the Google Analytics superProxy endpoint of Google App Engine
    cache_path: # the local PV cache data, friendly to visitors from GFW region

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
avatar: /assets/img/avatar/avatar.png

# boolean type, the global switch for TOC in posts.
toc: true

comments:
  active: gitalk # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo: # <gh-username>/<repo>
    issue_term: # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: # <gh-username>/<repo>
    repo_id:
    category:
    category_id:
    mapping: # optional, default to 'pathname'
    input_position: # optional, default to 'bottom'
    lang: # optional, default to the value of `site.lang`
    reactions_enabled: # optional, default to the value of `1`
  gitalk: # Gitalk options ›
    repo: quafoo-net.github.io # <owner>/<repo>
    client_id: a4ab2e60fcf26b4b4ab1 # GitHub Application Client ID
    client_secret: 4e5f6403af9123098f38f03fce6812db4fafbdf2 # GitHub Application Client Secret
    owner: quafoo-net # GitHub repo owner and collaborators, only these guys can initialize Gitalk discussions
    admin: quafoo-net # GitHub repo owner and collaborators, only these guys can initialize Gitalk discussions
    # The ID of a default issue. By default, Gitalk will generate a random ID for each page as its issue ID.
    # You can use this setting to make comments of Gitalk reusable.
    # e.g. 'pathname', 'title', 'url', 'og:title', 'og:url', 'og:image', 'twitter:title', 'twitter:url', 'twitter:image'
    id: location.pathname # optional, default to the value of `pathname`
    # The number of issues to be displayed on each page
    perPage: 30 # optional, default to the value of `30`
    labels: gitalk # optional, default to `['Gitalk']`
    pagerDirection: last # optional, default to `first`
    createIssueManually: false # optional, default to `false`
    distractionFreeMode: false # optional, default to `false`


# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
assets:
  self_host:
    enabled: # boolean, keep empty means false
    # specify the Jekyll environment, empty means both
    # only works if `assets.self_host.enabled` is 'true'
    env: # [development|production]

pwa:
  enabled: true # the option for PWA feature

paginate: 10

# ------------ The following options are not recommended to be modified ------------------

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

exclude:
  - "*.gem"
  - "*.gemspec"
  - tools
  - README.md
  - CHANGELOG.md
  - LICENSE
  - rollup.config.js
  - node_modules
  - package*.json

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/
